
# Playbook to install Sparta web server application on 'web' agent node
---
- hosts: web
# see the logs while the script is running so we can see the result
  gather_facts: yes
# provide admin access
  become: true
# outline tasks
## task 1 - update and upgrade agent node
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
## task 2 - install nxginx
  - name: Installing Nginx web server
    apt: pkg=nginx state=present
## task 3 - install node
  - name: Installing Node.js
    apt:
      name: nodejs
      state: present
## task 4 - install npm
  - name: Installing npm
    apt:
      name: npm
      state: present
## task 5 - clone app

  - name: clone app github repository
    git:
      repo: https://github.com/Ziziou91/tech258_cicd
      dest: /tech258_cicd
      clone: yes
      update: yes
## task 6 - install pm2
  - name: install pm2
    shell: |
      cd /tech258_cicd/app && npm install -y && npm install pm2 -g
