# Playbook to install Sparta web server application on 'web' agent node
---
- hosts: web
# see the logs while the script is running so we can see the result
  gather_facts: yes
# provide admin access
  become: true
# outline tasks
## task 1 - update and upgrade agent node
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
## task 2 - install nxginx
  - name: Installing Nginx web server
    apt: pkg=nginx state=present
## task 3 - install node
  - name: Installing Node.js
    apt:
      name: nodejs
      state: present

## task 4 - update and upgrade agent node
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

## task 5 - install npm
  - name: Installing npm
    apt:
      name: npm
      state: present

## task 6 - update and upgrade agent node
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day


## task 7 - clone app

  - name: clone app github repository
    git:
      repo: https://github.com/Ziziou91/tech258_cicd
      dest: /tech258_cicd
      clone: yes
      update: yes

## task 8 - set DB_HOST
  - name: set DB_host
    lineinfile:
      path: /etc/environment
      line: 'DB_HOST=mongodb://18.201.198.74:27017/posts'
      create: yes

## task 9 - install npm and pm2
  - name: install pm2
    shell: |
      cd /tech258_cicd/app
      sudo -E npm install --unsafe-perm
      npm install pm2@4.0.0 -g

## task 10 - launch app with pm2
  - name: launch app with pm2
    shell: |
      cd /tech258_cicd/app
      pm2 stop app
      pm2 start app.js
